spring:
  application:
    name: bff-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
              enabled: false
          routes:
            - id: iphone-api
              uri: lb://IPHONE
              predicates:
                - Path=/api/v1/iphones/**
              filters:
                - TokenRelay=
                - SaveSession
                - name: CircuitBreaker
                  args:
                    name: iphoneApiCircuit
                    fallbackUri: forward:/fallback/iphone-api

            - id: iphone
              uri: http://localhost:3001
              predicates:
                - Path=/iphone/**,/iphone-static/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: iphoneUiCircuit
                    fallbackUri: forward:/fallback/iphone
            - id: ipad
              uri: http://localhost:3002
              predicates:
                - Path=/ipad/**,/ipad-static/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: ipadUiCircuit
                    fallbackUri: forward:/fallback/ipad
            - id: macbook
              uri: http://localhost:3003
              predicates:
                - Path=/macbook/**,/macbook-static/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: macbookUiCircuit
                    fallbackUri: forward:/fallback/macbook
            - id: root
              uri: http://localhost:3000
              predicates:
                - Path=/**

    # configuration oauth2-client
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9999

      client:
        provider:
          itp-frontbff:
            issuer-uri: http://localhost:9999
        registration:
          itp-frontbff:
            provider: itp-frontbff
            client-id: itp-frontbff
            client-secret: qwerqwer
            redirect-uri: http://localhost:3333/login/oauth2/code/itp-frontbff
            authorization-grant-type:
              - authorization_code
            scope:
              - openid # Auto issue access token
              - profile # Get profile
              - email # Get email

resilience4j:
  circuitbreaker:
    instances:
      iphoneApiCircuit:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      iphoneUiCircuit:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      ipadUiCircuit:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
      macbookUiCircuit:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  timelimiter:
    instances:
      iphoneApiCircuit:
        timeoutDuration: 3s
      iphoneUiCircuit:
        timeoutDuration: 3s
      ipadUiCircuit:
        timeoutDuration: 3s
      macbookUiCircuit:
        timeoutDuration: 3s

server:
  port: 3333

eureka:
  instance:
    instance-id: ${spring.application.name}
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.event: TRACE
